routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Event;

Route::get('/', function () {
    $events = Event::all();
     return view('events.index')->withEvents($events);
});

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    public $timestamps = false;
    protected $fillable = ['nom', 'desc', 'lieu', 'prix','start_at'];

    // protected $dates = ['start_at']; //pr convertir start_at à une instance de type carbone( c'est comme DateTime mais c plus avancé)
    protected $casts = ['start_at' => 'datetime'];

    public function isFree()
    {
        return $this->prix == 0;
    }

    public function getPrixPlusAttribute()
    {
        return $this->attributes['prix'] + 100;
    }

    public function getPrixAttribute($value)
    {
        return $value;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/helpers.php
<?php
 //on p sup ce fic car on a creer un dos Helpers qui contient nos
 //helpers... mais on p le laisser en guise d'aide
if(! function_exists('formater_prix'))
{
    function formater_prix($evennement)
    {
        if($evennement->isFree())
        {
            return '<strong>GRATUIT!</strong>';
        }
        else
        {
            return sprintf('%.2f euros', $evennement->prix);
        }
    }
}

if(! function_exists('formater_date'))
{
    function formater_date($date)
    {
        return $date->format('d/m/Y H:i:s');
    }
}
?>

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/events/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Events</title>

</head>
<body>
    <h1> <center>{{ $events->count() }} Evennements</center></h1>

    @foreach($events as $evennement)
        <article>
            <h1> {{ $evennement->nom }}</h1>
            <p><u>Description</u> : {{ $evennement->desc }}</p>
            <p><u>Prix</u>: {!! $formater_prix($evennement) !!} </p>
            <p><u>Prix</u>: <strike>{{ $evennement->prix_plus }} </strike></p>
            <p><u>Lieu</u> :  {{ $evennement->lieu }}</p>
            <!-- <p><u>Date</u> :{{ $evennement->start_at->format('d/m/Y H:i:s') }}</p> -->
            <p><u>Date</u> :{{ $formater_date($evennement->start_at) }}</p>

            @if(! $loop->last)
                <hr>
            @endif
        </article>
        {{-- je suis un commentaire test --}}
    @endforeach
</body>
</html>